### ISSUE TITLE
希望能和各大oj联系更紧密，提供诸如自动submit等功能

### ISSUE THREAD

**Issue by flyingpig233-cpu** [onion108/oi_helper#2]
`codeforces`和`洛谷`等oj系统都提供了相应的api
洛谷：[https://github.com/0f-0b/luogu-api-docs](https://github.com/0f-0b/luogu-api-docs)

并参考现有项目如 [https://github.com/xalanq/cf-tool](https://github.com/xalanq/cf-tool)

**Comment by flyingpig233-cpu** [comment]
I made another one, so there is no need to use it.
Sorry

**Comment by onion108** [comment]
> I made another one, so there is no need to use it. Sorry

Maybe mine could work together with your cli 😃 
i.e. After you finishing your cli, I may add some features similar but need to call your CLI
or if you want to make your cli also a library? Then I can add this as one of my dependencies.

**Comment by flyingpig233-cpu** [comment]
Good idea.
So, merge?

**Comment by onion108** [comment]
> Good idea. So, merge?

i think so

**Comment by onion108** [comment]
You can make a pull request whenever you like, as long as you won't break my code style.

**Comment by onion108** [comment]
Don't forget to add document comments

**Comment by flyingpig233-cpu** [comment]
我认为有几个东西是没必要的，如workspace，它应该是可选的

**Comment by flyingpig233-cpu** [comment]
我创了个新项目，要来就看qq
